### ISSUE TITLE
Make table columns sortable on page `Analyze Message Data/Count Messages By User`

### ISSUE THREAD

**Issue by pconrad** [ucsb-cs156-s21/proj-mapache-search#89] opened 2020-12-12 05:08 UTC
# User Story

As a user I can sort the table columns on the  `Analyze Message Data/Count Messages By User` page so that I can sort either by username, or message frequency, ascending or descending.

# Acceptance Criteria

- [ ] There is a button at the top of each column to sort / ascending or descending by that column
- [ ] When I click those buttons, the columns sort accordingly.
- [ ] I can see a visual indicator of whether the columns are sorted or not, and that indicator works for both colorblind and non-colorblind users. 

...

# Implementation Todos

Follow the steps in this PR from the ucsb-cs-las project:  https://github.com/ucsb-cs156-f20/proj-ucsb-cs-las/pull/62/files

Front end:

- [ ] Add a `sortCaret` function as in the PR referenced above, to the component `javascript/src/main/components/UserMessages/UserChannelMessageList.js`
- [ ] Add ` sort: true, sortCaret: sortCaret` to each of the entries in the `columns` list 

Testing:
- [ ] Add a test for the sorting functionality as in `javascript/src/test/components/Courses/CourseTable.test.js` in the PR reference above, into the tests for the component `UserChannelMessageList`
- [ ] Existing front end tests pass and there is adequate coverage for new functionality

**Comment by andrewhlu** [comment] 2021-05-10 21:02
Duplicate of #171 which has already been resolved.

**Closed by andrewhlu** 2021-05-10 21:02 UTC
Labels: W21, good first issue
