### ISSUE TITLE
Message for a user over time.

### ISSUE THREAD

**Issue by ksbenipal** [ucsb-cs156-s21/proj-mapache-search#33] opened 2020-11-19 22:47 UTC
Message for a user over time.

As a member/admin I would like to see, for a specified user, a histogram of their level of activity on the slack by week (Sunday through Saturday). It probably works best if this histogram is vertical, i.e. the Y axis is time, from oldest at top to most recent at bottom, and the x axis is message count. It will take some experimentation to know what the right "scale" should be for the x axis; it would be helpful if that scale were consistent across all users.

# Acceptance Criteria

- [ ] A vertical histogram is given with the correct axis. For the specified users activity

**Comment by andrewhlu** [comment] 2021-05-10 20:46
Duplicate of #136.

**Closed by andrewhlu** 2021-05-10 20:46 UTC
