### ISSUE TITLE
/mapache teamlist: list all teams

### ISSUE THREAD

**Issue by Fluellen-Arman** [ucsb-cs156-s21/proj-mapache-search#51] opened 2020-12-02 23:40 UTC
# ./mapache teams

As a user I can type `/mapache teamlist` so that I can see a list of all the teams in the class. 

# Acceptance Criteria

- [x] When the user types `/mapache teamlist`, the bot should list all of the teams in the slack channel.
- [x] Existing functionality is unchanged (see below).

# Discussion

Currently, `/mapache teamlist` gives you an error, and `/mapache teamlist {team_name}` gives you a list of the emails of the members within that team. 

We should change this so that the `teamlist` command without an argument lists all the teams.
(If a second argument is added, the functionality remains unchanged.)

Back end:
- [x] add a function to process the /mapache teamlist command
- [x] make that command list all of the teams.

Testing:

- [x] Back end tests pass and there is adequate coverage

**Comment by andrewhlu** [comment] 2021-05-10 20:48
Potential duplicate of #26? May have to do some more investigation.

**Closed** 2021-05-26 02:25 UTC
Labels: S21-7pm-4-Admin
